import { expect, test } from '@playwright/test'

const PNG = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64')

/** Create, read, update and delete across a situation's life, ending with decision D1: delete after sending. */
test('situación nueva: evidencia, hecho propio, perfil, renombrar y eliminar tras enviar', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Entrar como persona' }).click()
  await page.getByRole('button', { name: '+ Registrar una situación' }).click()
  await page.getByLabel('Tu relato').fill('El 05/09/2026 mi jefe me gritó delante del equipo.')
  await page.getByLabel('Tu relato').blur()
  await page.waitForURL(/#\/s\/(?!nuevo)[^/]+\/registrar$/)

  const chooser = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: '+ Captura' }).click()
  await (await chooser).setFiles({ name: 'chat.png', mimeType: 'image/png', buffer: PNG })
  await page.getByRole('button', { name: 'Guardar evidencia' }).click()
  await page.getByRole('button', { name: 'Describir chat.png' }).click()
  await page.getByLabel(/Qué muestra chat.png/).fill('Mensaje recibido el 06/09/2026: «Ven a mi oficina».')
  await page.getByRole('button', { name: 'Guardar descripción' }).click()
  await expect(page.getByText('con descripción')).toBeVisible()

  await page.getByRole('button', { name: 'Entender lo ocurrido →' }).click()
  await expect(page.locator('.event-card').first()).toBeVisible({ timeout: 15000 })
  await page.getByRole('button', { name: /Agregar un hecho que VERA no detectó/ }).click()
  await page.getByLabel('Título').fill('Cambio de escritorio')
  await page.getByLabel('Qué ocurrió, con tus palabras').fill('Me cambiaron de escritorio sin aviso.')
  await page.getByRole('button', { name: 'Agregar hecho' }).click()
  const mine = page.getByRole('article', { name: 'Cambio de escritorio' })
  await expect(mine.getByText(/Agregado por ti/).first()).toBeVisible()
  await mine.getByRole('button', { name: 'Editar' }).click()
  await mine.getByLabel('Título').fill('Cambio de escritorio sin aviso')
  await mine.getByRole('button', { name: 'Guardar corrección' }).click()
  await expect(page.getByRole('article', { name: 'Cambio de escritorio sin aviso' })).toBeVisible()

  await page.getByRole('link', { name: /abrir mi perfil/ }).click()
  await page.getByLabel('Área').fill('Operaciones y logística')
  await page.getByRole('button', { name: 'Guardar perfil' }).click()
  await expect(page.getByText('Perfil guardado.')).toBeVisible()

  await page.goBack()
  await page.getByRole('button', { name: 'Preparar reporte →' }).click()
  await expect(page.locator('.fact', { hasText: 'Cambio de escritorio sin aviso' })).toBeVisible()
  await page.getByRole('button', { name: 'Revisar y compartir →' }).click()
  await page.getByRole('button', { name: 'Revisar lo que verá la organización' }).click()
  await page.getByText(/Entiendo que, al confirmar/).click()
  await page.getByRole('button', { name: 'Confirmar y enviar' }).click()
  const sent = page.getByRole('heading', { name: /Enviaste el caso V-\d{3}/ })
  await expect(sent).toBeVisible()
  const caseId = (await sent.innerText()).replace('Enviaste el caso ', '')

  await page.getByRole('button', { name: 'Volver a mi espacio' }).click()
  const card = page.getByRole('article', { name: 'Situación #002' })
  await card.getByRole('button', { name: 'Renombrar' }).click()
  await page.getByLabel('Nombre').fill('Gritos en la reunión')
  await page.getByRole('button', { name: 'Guardar nombre' }).click()
  const renamed = page.getByRole('article', { name: 'Gritos en la reunión' })
  await expect(renamed).toBeVisible()
  await renamed.getByRole('button', { name: 'Eliminar' }).click()
  await expect(page.getByRole('dialog').getByText(new RegExp(`Tu organización conserva el caso ${caseId}`))).toBeVisible()
  await page.getByRole('button', { name: 'Eliminar definitivamente' }).click()
  await expect(page.getByText('Situación eliminada de tu espacio.')).toBeVisible()
  await expect(page.getByRole('article', { name: 'Gritos en la reunión' })).toHaveCount(0)

  await page.getByRole('button', { name: 'Organización' }).click()
  await page.locator('.case-row', { hasText: caseId }).click()
  await expect(page.getByRole('heading', { name: `Caso ${caseId}` })).toBeVisible()
  await expect(page.locator('.case-detail').getByText('Cambio de escritorio sin aviso')).toBeVisible()
})
